### ISSUE TITLE
Code Postal vs Code Insee

### ISSUE THREAD

**Issue by chipsus** [ludaavics/pogam#10]
toutes mes requetes de recherche manuel sont bases sur le [ci ](https://seloger.com/list.htm?tri=initial&enterprise=0&idtypebien=2,1&pxMax=2000000&idtt=2,5&naturebien=1,2,4&ci=750117)et non plus sur [cp ](https://github.com/ludaavics/pogam/blob/3e8bb4bb903a2de5e9182215337b4e7845e4560d/pogam/scrapers/seloger.py#L180) (code insee vs code postal), donc je narrive pas a trouver la bonne nomenclature pour 75016 (tried 75016, 75116, 75016,75116, 75011)

fix:
il faut introduire l idee que le code postal peut etre un cp ou un ci, et que si cp=75016, then use ci=750116

Autre point, j'ai verifie sur un bien dont je connais l'adresse, 'mapPoly' a l'air de donner un lieu plus precis pour le bien
Pour ce bien j'ai 110 rue de la pompe, alors que l'adresse est 178 av victor hugo, a cote mais pas exactement ca

**Comment by ludaavics** [comment]
While seloger does seem to prefer code insee, i was under the impression it supported code postal as well but perhaps that was just dumb luck (or perhapse a bug on their side that goes unnoticed bc all the internals use code insee)

for pogam's api, i think only code postal makes sense. i don't know anyone who thinks in code insee.

I would suggest using [this data set](https://www.data.gouv.fr/en/datasets/correspondance-code-insee-code-postal/) to convert code postal to code insee. A side benefit is that it gives us latitude and longitude of every postal code, so we could use that as fall back on properties that don't have lat/long data

**Comment by chipsus** [comment]
Agreed, CP should be the input

The [data set](https://www.data.gouv.fr/en/datasets/correspondance-code-insee-code-postal/) has a 5 digits Code Insee, while seloger only reads 6 digits
ex: Neuilly sur seine, cp 92200, ci 92051, seloger reads [92**0**051](https://www.seloger.com/list.html?projects=2,5&types=1,2&natures=1,2,4&places=[{ci:920051}]&enterprise=0&qsVersion=1.0)

Either it's another variation of CI, or seloger just adds a 0 between the department (2 first digits) and the rest. so from CI=92051 to 92 * **0** * 051 

**to do**: map cp to ci, add the 0, then convert our url generator from cp to ci.
I can (try to) do it
