### ISSUE TITLE
multiple ci for one 5-digit post code. ex:80200

### ISSUE THREAD

**Issue by chipsus** [ludaavics/pogam#21]
https://github.com/ludaavics/pogam/blob/23ce851439773733c449dd3f840804359cf0978e/pogam/scrapers/seloger.py#L46

try 80200:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-179-c923428f2c5d> in <module>
     43         "This should never happen!"
     44     )
---> 45     raise RuntimeError(msg)

RuntimeError: Got multiple matches for post code '80200'. This should never happen!

----------------------------------------------------------------------------

It actually happens, 80200 is a postcode referencing to different ci (different cities?)
matches returns

_[('ci', '800015'), ('ci', '800017'), ('ci', '800033'), ('ci', '800034'), ('ci', '800054'), ('ci', '800080'), ('ci', '800090'), ('ci', '800102'), ('ci', '800115'), ('ci', '800128'), ('ci', '800141'), ('ci', '800150'), ('ci', '800154'), ('ci', '800177'), ('ci', '800197'), ('ci', '800199'), ('ci', '800239'), ('ci', '800240'), ('ci', '800267'), ('ci', '800289'), ('ci', '800288'), ('ci', '800557'), ('ci', '800294'), ('ci', '800304'), ('ci', '800307'), ('ci', '800313'), ('ci', '800430'), ('ci', '800509'), ('ci', '800536'), ('ci', '800552'), ('ci', '800555'), ('ci', '800620'), ('ci', '800701'), ('ci', '800741'), ('ci', '800750'), ('ci', '800801')]_

**fix**:
I suggest using only a cp=80200 and ignores the ci

How to recognise a cp ref to multiple ci ?
-->For these cp, cities first element is _{'Type': 'Group',_

We need to change or remove the Runtimeerror (why do we have this test ?)

**Comment by ludaavics** [comment]
Hah. Shortest lived "this should never happen" in a while. I didnt think multiple cities could have teh same post code, hence my "this should never happen"

 - I agree with you, i think in this case, we should return the match of type "Group", i.e. bundle allt he cities together.
 - do you want to take a stab at this PR? the first step would be to add a failing test, i.e. add a test case here: https://github.com/ludaavics/pogam/blob/42e990b121af227a0012c576106c92cd63a99b97/tests/test_seloger.py#L6-L19
 the `post_code` is "80200" and the `seloger_code` we would want to get back is `("cp", "80200")`. So just mess around with `_to_seloger_geographical_code` until you get that result.
 - how did you come across this example? Were you genuinely looking for listings in that area?
